# postgres-nessie.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-nessie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-nessie
  template:
    metadata:
      labels:
        app: postgres-nessie
    spec:
      containers:
        - name: postgres
          image: postgres:17.2-bookworm
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "nessie_db"
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: "1Gi"
              cpu: 100m
            requests:
              memory: "512Mi"
              cpu: 100m
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nessie-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-nessie